(function () {
  "use strict";

  window.PawsBelow = window.PawsBelow || {};

  window.PawsBelow.CONFIG = {
    tileSize: 16,
    tileChunkSize: 8,
    staticTerrainChunkCacheLimit: 384,
    worldWidth: 50,
    playerStartX: 24,
    surfaceY: 10,
    maxEnergy: 100,
    startingCoins: 0,
    infiniteCoinsAmount: 999999,
    dirtCarryCapacity: 5,
    dirtHealth: 5,
    pebbliteHealth: 18,
    pebbliteSpawnChance: 0.05,
    pebbliteValue: 3,
    coalclumpHealth: 22,
    coalclumpSpawnChance: 0.03,
    coalclumpValue: 5,
    copperpawHealth: 35,
    copperpawSpawnChance: 0.01,
    copperpawValue: 10,
    oreDiscoveryPopupSeconds: 4.4,
    moveEnergyCost: 1,
    inputRepeatMs: 92,
    moveCooldownMs: 92,
    miningStrokeCooldownMs: 138,
    miningStrokeRadiusTiles: 3.1,
    miningStrokeConeDegrees: 58,
    miningStrokeDamageScale: 1.18,
    miningStrokeBaseTargets: 4,
    miningStrokeMaxTargets: 5,
    miningStrokeEnergyCostScale: 0.45,
    interactPromptPulseSeconds: 0.18,
    mainMenuHoldSeconds: 1.5,
    mainMenuFadeSeconds: 0.72,
    mainMenuSpriteSrc: "./assets/mainmenu.png",
    mainMenuMusicSrc: "./sound/mainmenu.mp3",
    mainMenuMusicVolume: 0.2208,
    mainMenuImageScale: 0.94,
    inventoryFullWarningSeconds: 0.95,
    moveAnimationMs: 92,
    digMoveAnimationMs: 128,
    digDownMoveAnimationMs: 142,
    surfaceWalkTilesPerSecond: 12.4,
    tileHitShakeMs: 150,
    crackGrowMs: 130,
    blockBreakShrinkMs: 170,
    tabbyDialogOpenSeconds: 0.22,
    tabbyDialogCloseSeconds: 0.14,
    upgradeUIOpenSeconds: 0.22,
    upgradeUICloseSeconds: 0.14,
    surfaceReturnFadeSeconds: 0.22,
    areaTransitionFadeSeconds: 0.72,
    pawUpgradeCost: 50,
    storageUpgradeCost: 50,
    staminaUpgradeCost: 50,
    pawBasePower: 1,
    pawLevel2Power: 1.4,
    pawLevel3Power: 2,
    pawLevel4Power: 2.5,
    pawLevel5Power: 5,
    pawMaxLevel: 5,
    tabbyDialogCharsPerSecond: 22.4,
    tabbyDialogTexts: [
      "WHAT? A visitor...",
      "Oh right. They said you'd come. You're a bit smaller than i expected",
      "Last time i saw a kitty your size was at the local orphanage...",
      "Ah well. Look... This town has been in desperate need of someone with your... skills",
      "We've been low on resources lately and the ancient myth claims a powerful source can be found deep into the earth.",
      "Nobody knows if it's true but... WORTH A TRY",
      "WHY ARE YOU STILL HERE? GO DIG CAT!"
    ],
    diggaPawsDialogTexts: [
      "Well, ittle one. Looks like you have yourself quite the mittens.",
      "Not so bad for diggin' the worms but if you want to head deeper you'll need some heavy duty tools.",
      "Why don't you head over into town? Just zzip past behind me and you'll be there in no time.",
      "Look around for Aunt Sanders. She will be of assistance to you. Good luck Have Fun Don't Die."
    ],
    cameraZoom: 2.5168,
    cameraFollowSpeed: 4.2,
    cameraVerticalOffsetTiles: -2,
    catGroundOffset: 8,
    catSheetGroundOffset: 8,
    catVisualTileSize: 32,
    surfaceVisualTileSize: 32,
    surfacePropGroundOffset: 8,
    cabinGroundSink: 12,
    cabinSpriteAspectRatio: 1.204,
    cabinInteractCenterX: 2.35,
    cabinInteractDistance: 3.2,
    cabinRainWindowGlowAlpha: 1.08,
    chimneySmokeOffsetX: 0.65,
    chimneySmokeOffsetY: 0.125,
    chimneySmokeIntervalSeconds: 0.16,
    dayNames: [
      "MONDAY",
      "TUESDAY",
      "WEDNESDAY",
      "THURSDAY",
      "FRIDAY",
      "SATURDAY",
      "SUNDAY"
    ],
    rainStreakCount: 88,
    rainSpeed: 430,
    rainSlant: 3,
    rainParallaxX: 0.28,
    rainParallaxY: 0.08,
    storageCapacities: [
      5,
      12,
      25,
      75,
      175,
      350
    ],
    staminaCapacities: [
      100,
      200,
      400,
      650,
      1000
    ],
    catSpriteSrc: "./assets/cat-sprite.png",
    catIdleSpriteSrc: "./assets/cat-idle.png",
    catIdleFrameColumns: 5,
    catIdleFrameRows: 5,
    catIdleFrameCount: 25,
    catIdleFramesPerSecond: 7,
    catIdleScale: 1.3,
    catRunSpriteSrc: "./assets/cat-run.png",
    catRunFrameColumns: 5,
    catRunFrameRows: 5,
    catRunFrameCount: 25,
    catRunFramesPerSecond: 18,
    catRunScale: 1.365,
    dirtSpriteSrc: "./assets/dirt.png",
    pebbliteSpriteSrc: "./assets/pebblite.png",
    coalclumpSpriteSrc: "./assets/coalclump.png",
    copperpawSpriteSrc: "./assets/copperpaw.png",
    grassSpriteSrc: "./assets/grass.png",
    currencyUISpriteSrc: "./assets/currencyUI.png",
    grassForegroundHeight: 21,
    grassForegroundSink: 13,
    grassForegroundOpacity: 0.5,
    cabinSpriteSrc: "./assets/cabin.png",
    scratchingPostSpriteSrc: "./assets/scratchingpost.png",
    scratchingPostHeightTiles: 1.56,
    scratchingPostOffsetXTiles: 0.36,
    scratchingPostGroundSink: 4,
    blacksmithSpriteSrc: "./assets/blacksmith.png",
    blacksmithHeightTiles: 5.2635,
    blacksmithGroundSink: 12,
    blacksmithChimneySmokeOffsetX: 0.56,
    blacksmithChimneySmokeOffsetY: 0.12,
    blacksmithInteractDistance: 2.3,
    blacksmithUIOpenSeconds: 0.2,
    blacksmithUICloseSeconds: 0.14,
    auntSandersSpriteSrc: "./assets/auntsanders.png",
    blacksmithMenuBackgroundSrc: "./assets/blacksmithtexture.png",
    blacksmithMenuScale: 1.3,
    blacksmithUnlockEffectSeconds: 0.9,
    blacksmithIntroOpenSeconds: 0.26,
    blacksmithIntroCloseSeconds: 0.16,
    blacksmithIntroTexts: [
      "Well if it ain't the lil miner everyone been raging about",
      "Judging by your pathetic empty-handedness, you want me to whip you up a pickaxe.",
      "Well...you're at the right place, child. Just say the word and you're equipped."
    ],
    pickaxeUpgradeCosts: [
      75,
      150,
      300,
      600,
      1200,
      2400,
      4800,
      9600,
      19200
    ],
    pickaxeOreDamageScale: 1.3,
    pickaxeUpgrades: [
      { name: "Pebblite Pick", strength: 1.2, iconSrc: "./assets/pebblitepick.png" },
      { name: "Copperpaw Pick", strength: 1.8, iconSrc: "./assets/copperpawpick.png" },
      { name: "Ironfang Pick", strength: 2.4, iconSrc: "./assets/ironfangpick.png" },
      { name: "Quartz Pick", strength: 3, iconSrc: "./assets/quartzpick.png" },
      { name: "Goldpurr Pick", strength: 3.6, iconSrc: "./assets/goldpurrpick.png" },
      { name: "Xeno Pick", strength: 4.2, iconSrc: "./assets/xenogreenpick.png" },
      { name: "Opal Pick", strength: 4.8, iconSrc: "./assets/opalfoampick.png" },
      { name: "Heartcore Pick", strength: 5.4, iconSrc: "./assets/heartcorepick.png" },
      { name: "Meowtanium Pick", strength: 6, iconSrc: "./assets/meowtaniumpick.png" }
    ],
    townBuildingGapTiles: 0.35,
    museumSpriteSrc: "./assets/museum.png",
    museumHeightTiles: 6.2205,
    museumGroundSink: 24,
    museumInteractDistance: 2.7,
    orphanageSpriteSrc: "./assets/orphanage.png",
    orphanageHeightTiles: 6.2205,
    orphanageGroundSink: 24,
    outhouseSpriteSrc: "./assets/outhouse.png",
    outhouseHeightTiles: 3.48,
    outhouseGroundSink: 18,
    outhouseOffsetFromRightTiles: -0.45,
    outhouseInteractDistance: 1.35,
    outhouseOccupiedBubbleSeconds: 1.4,
    compendiumSpriteSrc: "./assets/compendium.png",
    compendiumUIOpenSeconds: 0.2,
    compendiumUICloseSeconds: 0.14,
    upgradeUISpriteSrc: "./assets/SoftPaws.png",
    upgradedUpgradeUISpriteSrc: "./assets/Paws.png",
    toughUpgradeUISpriteSrc: "./assets/ToughPaws.png",
    maxUpgradeUISpriteSrc: "./assets/MaxPaws.png",
    diggaUpgradeUISpriteSrc: "./assets/diggapaws.png",
    toughUpgradeUISpriteScale: 0.96,
    maxUpgradeUISpriteScale: 0.84,
    fannyUpgradeUISpriteSrc: "./assets/fanny.png",
    bucketUpgradeUISpriteSrc: "./assets/bucket.png",
    backpackUpgradeUISpriteSrc: "./assets/backpack.png",
    crateUpgradeUISpriteSrc: "./assets/crate.png",
    duffelUpgradeUISpriteSrc: "./assets/duffel.png",
    treasureChestUpgradeUISpriteSrc: "./assets/treasurechest.png",
    staminaUpgradeUISpriteSrcs: [
      "./assets/fish.png",
      "./assets/energybarfood.png",
      "./assets/Cake.png",
      "./assets/sugar.png",
      "./assets/adrenaline.png"
    ],
    signSpriteSrc: "./assets/mewberry.png",
    tabbySpriteSrc: "./assets/tabby.png",
    treeSpriteSrc: "./assets/tree.png",
    treeHeightTiles: 5.64,
    treeOffsetXTiles: -2.4,
    treeGroundSink: 5,
    treeSignHeightTiles: 1.48,
    treeSignOffsetXTiles: -1.08,
    backgroundTreeCount: 7,
    backgroundTreeAlpha: 0.38,
    fallingLeafIntervalSeconds: 0.88,
    textboardSpriteSrc: "./assets/textboard.png",
    skyboxSpriteSrc: "./assets/skybox.png",
    skyboxOpacity: 0.3,
    skyUnderlay: "#aee8ff",
    upgradeMenuBackgroundSrc: "./assets/wooden.png",
    surfaceAmbienceSrc: "./sound/ambience.mp3",
    surfaceAmbienceStartSeconds: 2,
    surfaceAmbienceVolume: 0.42,
    ambienceVolumeScale: 1,
    effectsVolumeScale: 1,
    diggingVolumeScale: 1,
    surfaceAmbienceFadeDepth: 8,
    surfaceAmbienceLoopLeadSeconds: 0.08,
    rainAmbienceSrc: "./sound/rain.mp3",
    rainAmbienceVolume: 0.10584,
    backToSurfaceSoundSrc: "./sound/backtosurface.mp3",
    backToSurfaceSoundVolume: 0.55,
    doorOpenSoundSrc: "./sound/dooropen.mp3",
    doorCloseSoundSrc: "./sound/doorclose.mp3",
    doorOpenSoundVolume: 0.2352,
    doorCloseSoundVolume: 0.2744,
    luckUpgradeSoundSrc: "./sound/luckupgrade.mp3",
    luckUpgradeSoundVolume: 0.2592,
    rockBreakSoundSrcs: [
      "./sound/rockbreak1.mp3",
      "./sound/rockbreak2.mp3",
      "./sound/rockbreak3.mp3"
    ],
    rockBreakSoundVolume: 0.3472,
    luckAmbienceSrc: "./sound/luckambience.mp3",
    luckAmbienceVolume: 0.272,
    grassRunSoundIntervalSeconds: 0.216,
    windStreakCount: 10,
    windStreakPeriodSeconds: 5.6,
    windStreakMaxAlpha: 0.42,
    windStreakLineWidth: 2,
    butterflyCount: 7,
    butterflyOpacity: 0.3,
    butterflyScale: 0.7,
    butterflyFadeSpeed: 3.2,
    butterflySurfaceHeight: 72,
    butterflySpeed: 9,
    fireflyCount: 16,
    fireflyOpacity: 0.52,
    fireflySurfaceHeight: 78,
    fireflySpeed: 7,
    shrineSpriteSrc: "./assets/shrine.png",
    shrineHeightTiles: 3.055,
    shrineOffsetXTiles: 1.35,
    shrineGroundSink: 6,
    shrineInteractDistance: 2.25,
    luckBackgroundSpriteSrc: "./assets/luckbackground.png",
    luckUISpriteSrc: "./assets/luckUI.png",
    luckUIOpenSeconds: 0.2,
    luckUICloseSeconds: 0.14,
    maxLuckPercent: 1000,
    luckFlowerSpriteSrcs: [
      "./assets/luckflower.png",
      "./assets/luckflower2.png"
    ],
    luckFlowerCount: 22,
    luckFlowerHeightTiles: 0.68,
    luckFlowerOpacity: 0.8,
    bugSpriteSrcs: [
      "./assets/bug1.png",
      "./assets/bug2.png",
      "./assets/bug3.png"
    ],
    undergroundBugCount: 6,
    undergroundBugHeight: 16,
    undergroundBugMinDepth: 3,
    tabbyInteractDistance: 2.5,
    cloudSpriteSrcs: [],
    cloudSpriteYOffset: [
      26,
      0
    ],
    resetFadeSeconds: 0.55,
    seed: 41973,
    colors: {
      skyTop: "#0385fa",
      skyBottom: "#82c8f8",
      tunnel: "#4b3325",
      tunnelDark: "#322419",
      dirt: "#8b5d3d",
      dirtDark: "#60432e",
      dirtLight: "#aa7650",
      grass: "#4c934f",
      grassLight: "#8ed061"
    }
  };
})();
